export const enum InputAction {
    Sync = "sync",
    DeleteTime = "deleteTime",
    ResetOffset = "resetOffset",
    DecreaseOffset = "decreaseOffset",
    IncreaseOffset = "increaseOffset",
    PrevLine = "prevLine",
    NextLine = "nextLine",
    FirstLine = "firstLine",
    LastLine = "lastLine",
    PageUp = "pageUp",
    PageDown = "pageDown",
    SeekBackward = "seekBackward",
    SeekForward = "seekForward",
    ResetRate = "resetRate",
    IncreaseRate = "increaseRate",
    DecreaseRate = "decreaseRate",
    TogglePlay = "togglePlay",
    ShowHelp = "showHelp",
}
